<a href="https://colab.research.google.com/github/Md-Salman-Rahman339/AI-ML/blob/main/DataAnalysisNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np

arr1=np.array([1,2,3,4,5])
# arr1=arr1 * 5
# print(arr1)
arr2=np.array([[1,2,3],[4,5,6]])
# print(arr2)
arr3 = np.array([
    #1st floor
    [ [1,2,3], # row1
      [4,5,6]  ], #row2

    #2nd floor

     [[1,2,3], # row1
      [4,5,6]  ], #row2


    #3rd floor
      [[1,2,3], # row1
      [4,5,6]  ] #row2


])
# print(arr3)
# print(arr3.shape)
# print(arr3.ndim)
# print(arr3.size)
# print(arr3.dtype)

lst=[10,20,30,40,40.5]
arr=np.array(lst,dtype=np.int32)
# print(arr)
# print(arr.dtype)
mixed_list=[10,True,'Hello']
arr=np.array(mixed_list)
# print(arr)
# print(arr.dtype)

matrix=[[1,2,3],[4,5,6]]
arr=np.array(matrix)
# print(arr)

dc={'a':10,'b':20,'c':30}
keys=dc.keys()
values=dc.values()
items=dc.items()
arr=np.array(list(values))
# print(arr)

[10 20 30]


In [17]:
arr=np.zeros((2,3),dtype=np.int8)
# print(arr)
arr=np.zeros_like(arr3)
# print(arr)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


In [20]:
arr=np.ones((3,4,3),dtype=np.int8)
# print(arr)
arr=np.ones_like(arr3)
# print(arr)
# print(arr.shape)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(3, 2, 3)


In [23]:
#np.empty
arr = np.empty((4,3),dtype=np.int8)
# print(arr)
arr = np.empty_like(arr3)
print(arr)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [25]:
arr=np.full((4,3),np.inf)
# print(arr)
arr=np.full_like(arr3,np.inf,dtype=np.float64)
print(arr)

[[[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]]


In [26]:
arr=np.random.rand(2,3)
print(arr)

[[0.82430665 0.96395212 0.6558192 ]
 [0.53294823 0.7776064  0.54974203]]


In [28]:
arr=np.random.randint(1,100,(2,3))
print(arr)

[[51 58 73]
 [82 45 14]]


In [32]:
arr=np.arange(1,10,1)
print(arr)
mat=arr.reshape(3,3)
print(mat)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
arr=np.linspace(0,4,6)
print(arr)

[0.  0.8 1.6 2.4 3.2 4. ]


In [37]:
arr=np.logspace(0,4,5,base=2)
print(arr)

[ 1.  2.  4.  8. 16.]


In [39]:
diagonal_matrix=np.diag([1,2,3,4])
print(diagonal_matrix)
print(diagonal_matrix.shape)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
(4, 4)


In [40]:
identity_matrix=np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [42]:
print(arr1)
print(arr2)
arr2[0][2]=100
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[  1   2 100]
 [  4   5   6]]


In [48]:
row_0=arr2[0:1,]
# print(row_0)
row_1=arr2[1,]
# print(row_1)
col_0=arr2[::,0:1]
print(col_0
      )
col_1=arr2[::,1:2]
print(col_1)


[[1]
 [4]]
[[2]
 [5]]


In [50]:
lst = np.array([ 10 , 20 ,30 ,40 ])

values = lst[[0,3,1]]

print(values)

[10 40 20]
