<a href="https://colab.research.google.com/github/Md-Salman-Rahman339/AI-ML/blob/main/DataAnalysisWithNumpypart2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

arr=np.random.randint(1,100,size=(10,5))
print(arr)

[[81 32 37 18  8]
 [76 31 61 34 52]
 [45  7 55 54 67]
 [56  7 47 17 75]
 [37 95 21 92 22]
 [18 60 82 70 25]
 [72 22 13 49 68]
 [44 64 40 77 39]
 [82 56 38 85  4]
 [64 14 38 20 10]]


In [2]:
arr.shape

(10, 5)

In [4]:
b=arr.reshape(5,10)
b
b.ndim

2

In [8]:
flatten=b.flatten()
print(flatten)
column_wise=np.ravel(b,order='C')
print(column_wise)

[81 32 37 18  8 76 31 61 34 52 45  7 55 54 67 56  7 47 17 75 37 95 21 92
 22 18 60 82 70 25 72 22 13 49 68 44 64 40 77 39 82 56 38 85  4 64 14 38
 20 10]
[81 32 37 18  8 76 31 61 34 52 45  7 55 54 67 56  7 47 17 75 37 95 21 92
 22 18 60 82 70 25 72 22 13 49 68 44 64 40 77 39 82 56 38 85  4 64 14 38
 20 10]


In [14]:
a = np.random.randint(1 ,10 , size =(2,3))
b = np.random.randint(20 ,30 , size =(2,3))
print(a)
print(b)


[[7 8 1]
 [9 3 1]]
[[23 21 26]
 [25 24 20]]


In [13]:
con_row=np.concatenate((a,b),axis=0)
print(con_row)
con_col=np.concatenate((a,b),axis=1)
print(con_col)

[[ 7  4  7]
 [ 9  2  1]
 [25 28 28]
 [25 24 25]]
[[ 7  4  7 25 28 28]
 [ 9  2  1 25 24 25]]


In [15]:
m=np.array([[1,2,3],
            [4,5,6]])
transpose=m.T
print(transpose)

[[1 4]
 [2 5]
 [3 6]]


In [9]:
x=np.array([1,2,3,4,5,6])

In [16]:
y=np.array([7,8,9,10,11,12])
sin_val = np.sin(y)
print(sin_val)
cos_val=np.cos(x)
print(cos_val)
log_2=np.log2(x)
print(log_2)
s=np.sum(x)
print(s)


[ 0.6569866   0.98935825  0.41211849 -0.54402111 -0.99999021 -0.53657292]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029]
[0.         1.         1.5849625  2.         2.32192809 2.5849625 ]
21


In [22]:
x = np.array([ 10 , 8 , 16 , 100 ])
z=x.copy()
print(z)
z.sort()

print(z)

print(x)

[ 10   8  16 100]
[  8  10  16 100]
[ 10   8  16 100]


In [25]:
# 2d array sorting
mat = np.array([[10,3,5]
                ,[8,4,9]])
hor_sort=np.sort(mat,axis=1)
print(hor_sort)
vertic_sort=np.sort(mat,axis=0)
print(vertic_sort)

[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


In [29]:
print(x)
index=np.where(x==100)
print(index)
arr=np.where(x>8,x,0)
print(arr)


[ 10   8  16 100]
(array([3]),)
[ 10   0  16 100]


In [32]:
print(mat)

[[10  3  5]
 [ 8  4  9]]


In [34]:

index=np.where(mat>8)
print(index)
arr=np.where(mat>8,mat,0)
print(arr)

(array([0, 1]), array([0, 2]))
[[10  0  0]
 [ 0  0  9]]


In [35]:
data=np.genfromtxt('student_scores.csv',delimiter=',',skip_header=1)
print(data)

[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]


In [41]:
math_marks=data[::,:1]
# print(math_marks)
# print(math_marks.T)
max_marks=np.max(math_marks)
print(max_marks)
min_marks=np.min(math_marks)
print(min_marks)
median_marks=np.median(math_marks)
print(median_marks)
std_math_marks = np.std(math_marks)
print(std_math_marks)

95.0
45.0
73.5
13.788672887555204


In [42]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

dot_product=np.dot(A,B)
print(dot_product)

[[ 58  64]
 [139 154]]
