<a href="https://colab.research.google.com/github/Md-Salman-Rahman339/AI-ML/blob/main/MidTerm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# mnayeem2310484@bscse.uiu.ac.**bd**

In [5]:
# You must run this code and use that data set for all the questions
import numpy as np
import pandas as pd

np.random.seed(42)

ids = np.arange(1, 11)
ages = np.random.randint(18, 60, 10)
salaries = np.random.randint(30000, 90000, 10)
departments = np.array(["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT", "Sales", "HR"])

DF = pd.DataFrame({
"id": ids,
"age": ages,
"salary": salaries,
"dept": departments
})

DF.to_csv("employees.csv", index=False)
print("Sample Data Created and Saved as employees.csv")


Sample Data Created and Saved as employees.csv


## Anst to the Q1


In [ ]:
a=np.array(ages)
s=np.array(salaries)

print("age details: ")
print(a)
print(a.dtype)
print(a.ndim)
print(a.shape)
print(a.size)
print("salary details: ")
print(s)
print(s.dtype)
print(s.ndim)
print(s.shape)
print(s.size)

age details: 
[56 46 32 25 38 56 36 40 28 28]
int64
1
(10,)
10
salary details: 
[77191 74131 46023 71090 31685 30769 89735 86101 32433 35311]
int64
1
(10,)
10


### answer to Q2

In [ ]:
higest_salary=np.max(salaries)
lowest_salaries=np.min(salaries)
average_salary=np.mean(salaries)
avg_age=np.mean(ages)
print(higest_salary)
print(lowest_salaries)
print(average_salary)
print(avg_age)


89735
30769
57446.9
38.5


## answer to Q3:

In [ ]:
ag=np.array(ages)
greater=ag>30
print(greater)
g=ag[greater]
print(g)
count=np.count_nonzero(g)
print("employees are older than 30 :",count)

[ True  True  True False  True  True  True  True False False]
[56 46 32 38 56 36 40]
employees are older than 30 : 7


## Answer to Q4

In [ ]:
agess=np.array(ages)
agg=agess+5
print(agess)
print(agg)

[56 46 32 25 38 56 36 40 28 28]
[61 51 37 30 43 61 41 45 33 33]


## Answer to Q5:

In [ ]:
sal=np.array(salaries)
print(sal)
saal=np.sum(sal)
print("Total Salary: ", saal)
sub=np.subtract(higest_salary,lowest_salaries)
print("difference between the maximum and minimum salary :",sub)

[77191 74131 46023 71090 31685 30769 89735 86101 32433 35311]
Total Salary:  574469
difference between the maximum and minimum salary : 58966


##  Pandas — 5 Questions

## Answer to the Q6:

In [ ]:
df=pd.read_csv("employees.csv")

print(df.head(5))
print(df.info())
print(df.describe())

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      10 non-null     int64 
 1   age     10 non-null     int64 
 2   salary  10 non-null     int64 
 3   dept    10 non-null     object
dtypes: int64(3), object(1)
memory usage: 452.0+ bytes
None
             id       age        salary
count  10.00000  10.00000     10.000000
mean    5.50000  38.50000  57446.900000
std     3.02765  11.16791  24357.262884
min     1.00000  25.00000  30769.000000
25%     3.25000  29.00000  33152.500000
50%     5.50000  37.00000  58556.500000
75%     7.75000  44.50000  76426.000000
max    10.00000  56.00000  89735.000000


## Answer to the  Q7:

In [13]:
selected_columns=df[['id', 'age','salary']]
print(selected_columns.to_string(index=False))
print(selected_columns.tail(3).to_string(index=False))

 id  age  salary
  1   56   77191
  2   46   74131
  3   32   46023
  4   25   71090
  5   38   31685
  6   56   30769
  7   36   89735
  8   40   86101
  9   28   32433
 10   28   35311
 id  age  salary
  8   40   86101
  9   28   32433
 10   28   35311


## Answer to Q8:

In [19]:
work_at=df.loc[df['dept']=='IT']
print(work_at)
count=work_at['id'].count()
print("Number of employee :",count)


   id  age  salary dept
1   2   46   74131   IT
3   4   25   71090   IT
7   8   40   86101   IT
Number of employee : 3


# Answer to Q9:

In [23]:
sorted=df.sort_values(['salary'],ascending=False)
top=sorted.head(3)
print(top)


   id  age  salary     dept
6   7   36   89735  Finance
7   8   40   86101       IT
0   1   56   77191       HR


## Answer to Q10:

In [36]:
  df.loc[df['salary']>80000,'salary']=80000
  avg_sal=df['salary'].mean()
  print(avg_sal)



55863.3
